Models/ErrorViewModel.cs
namespace projectclass.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/mydb.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace projectclass.Models
{
    public class mydb : DbContext
    {
        public mydb(DbContextOptions<mydb>options):base(options) { }
        public DbSet<register> registers { get; set; }
    }
}

Models/register.cs
using System.ComponentModel.DataAnnotations;

namespace projectclass.Models
{
    public class register
    {
        [Key]
        public int r_id { get; set; }
        public string r_name { get; set; }

        public string r_email { get; set; }
        public string r_pass { get; set; }


    }
}

Controllers/adminController.cs
using Microsoft.AspNetCore.Mvc;
using projectclass.Models;

namespace projectclass.Controllers
{
    public class adminController : Controller
    {
        private readonly mydb db;
        public adminController(mydb db)
        {
            this.db= db;
        }
        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult login(register r)
        {
            var check=db.registers.Where(a=>a.r_email ==r.r_email & a.r_pass == r.r_pass).FirstOrDefault();
            if(check != null)
            {
                return RedirectToAction("dashboard");

            }
            else
            {
                ViewBag.msg = "not login";
            }
            return View();
        }
        public IActionResult register()
        {
            return View();
        }
        public IActionResult dashboard()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projectclass</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/projectclass.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">projectclass</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - projectclass - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/admin/login.cshtml
@model register
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Login - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/adminlib/assets/img/favicon.png" rel="icon">
  <link href="~/adminlib/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/adminlib/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <!-- Template Main CSS File -->
  <link href="~/adminlib/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="~/adminlib/assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">NiceAdmin</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your username & password to login</p>
                  </div>

                  <form asp-controller="admin" asp-action="login" method="post" class="row g-3 needs-validation" novalidate>

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Email</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend"></span>
                        <input type="text" asp-for="r_email" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please enter your username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" asp-for="r_pass" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a asp-controller="admin" asp-action="register">Create an account</a></p>
                    </div>
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/adminlib/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/adminlib/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/adminlib/assets/vendor/chart.js/chart.umd.js"></script>
  <script src="~/adminlib/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/adminlib/assets/vendor/quill/quill.js"></script>
  <script src="~/adminlib/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/adminlib/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/adminlib/assets/vendor/php-email-form/validate.js"></script>


  <!-- Template Main JS File -->
  <script src="~/adminlib/assets/js/main.js"></script>

</body>

</html>
@{
    if (ViewBag != null)
    {
        <script>

            Swal.fire({
                icon: "error",
                title: "Incorrect...",
                text: "Does not match!",
            
            });

        </script>
    }
}

Views/admin/register.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Register - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/adminlib/assets/img/favicon.png" rel="icon">
  <link href="~/adminlib/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/adminlib/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/adminlib/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="~/adminlib/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="~/adminlib/assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">NiceAdmin</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                    <p class="text-center small">Enter your personal details to create account</p>
                  </div>

                  <form class="row g-3 needs-validation" novalidate>
                    <div class="col-12">
                      <label for="yourName" class="form-label">Your Name</label>
                      <input type="text" name="name" class="form-control" id="yourName" required>
                      <div class="invalid-feedback">Please, enter your name!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourEmail" class="form-label">Your Email</label>
                      <input type="email" name="email" class="form-control" id="yourEmail" required>
                      <div class="invalid-feedback">Please enter a valid Email adddress!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend"></span>
                        <input type="text" name="username" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please choose a username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" name="terms" type="checkbox" value="" id="acceptTerms" required>
                        <label class="form-check-label" for="acceptTerms">I agree and accept the <a href="#">terms and conditions</a></label>
                        <div class="invalid-feedback">You must agree before submitting.</div>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Create Account</button>
                    </div>
                    <div class="col-12">
                <p class="small mb-0">Already have an account? <a asp-controller="admin" asp-action="login">Log in</a></p>
                    </div>
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/adminlib/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/adminlib/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/adminlib/assets/vendor/chart.js/chart.umd.js"></script>
  <script src="~/adminlib/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/adminlib/assets/vendor/quill/quill.js"></script>
  <script src="~/adminlib/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/adminlib/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/adminlib/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/adminlib/assets/js/main.js"></script>

</body>

</html>